[package]
name = "dh-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }    


[lib]
crate-type = ["cdylib", "rlib"]